[package]
name = "mijia"
version = "0.3.1"
authors = ["Luis Félix <lcs.felix@gmail.com>", "Andrew Walbran <qwandor@google.com>", "David Laban <alsuren@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A library for connecting to Xiaomi Mijia 2 Bluetooth temperature/humidity sensors."
repository = "https://github.com/alsuren/mijia-homie/"
keywords = ["ble", "bluetooth", "humidity", "temperature"]
categories = ["hardware-support"]

[dependencies]
bluez-async = { version = "0.2.0", path = "../bluez-async" }
futures = "0.3.8"
log = "0.4.11"
thiserror = "1.0.23"
tokio = "1.0.1"
tokio-stream = "0.1.1"
uuid = "0.8.1"

[dev-dependencies]
chrono = "0.4.19"
eyre = "0.6.5"
pretty_env_logger = "0.4.0"
tokio = { version = "1.0.1", features = ["macros", "rt", "rt-multi-thread", "time"] }
